### ISSUE TITLE
adding a Why section.

### ISSUE THREAD

**Issue by luxus** [jmgilman/nixago#7]
hello,
I would recommend adding a Why section to your readme. Helping to understand the benefits is sometimes more important then the features

**Comment by jmgilman** [comment]
Thanks for the feedback! I've updated the documentation to better reflect the intended use-case of Nixago.

**Comment by luxus** [comment]
Thanks for the update. I hope I'm not too harsh; I'm coming from sales and see many good nix projects failed to sell themself. So I'm here to help.
A why section helps me understand how it could benefit. Even if I don't have any problem. For example, I don't have a cluttered root folder :D but I use dev tools and want a good start in the nix world.  Maybe when the project matures, we will have a real-life example
